server:
  port: 5001
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: >-
      jdbc:mysql://localhost:3307/testSystem?useUnicode=true
      &characterEncoding=utf8
      &useSSL=false
      &useLegacyDatetimeCode=false
      &serverTimezone=GMT%2B8
    username: root
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:5000/.well-known/jwks.json
